export_file(
    name = 'find-deps.js',
    src = 'find-deps.js',
    visibility = ['PUBLIC']
)

export_file(
    name = 'locate-bin.js',
    src = 'locate-bin.js',
    visibility = ['PUBLIC']
)

export_file(
    name = 'rules.build_defs',
    src = 'rules.build_defs',
    visibility = ['PUBLIC']
)